print("Did you hear the joke about the roof")
input()
print("Eh it's over your head")
name1=input("what is your name?")
input()
print(f"funny joke {name1} ha ha ha")
name1=input("tell me a joke")
print(f"that joke {name1} is great")
print(f"do you want to hear another {name1}")
if=input=("yes")
if=input=("no")
input()
print(f"thats great what do you call a train full of bubbel gum")
print(f"Im in your house {name1} let me tell you a story is not a joke")