print("Did you hear the joke about the roof")
input()
print("Eh it's over your head")
name1=input("what is your name?")
print(f"funny joke {name1} ha ha ha")
name2=input("tell me a joke")
print(f"that joke {name1} is great")
answer1=input(f"do you want to hear another {name1}")
if answer1 == " yes":
      print(f"thats great what do you call a train full of bubbel gum")
      print("you bum you knew the answer")
      input()
      print("a chew chew train ha ha ha")
      print("well I have to go i enjoyed talking to you goodbye")
if answer1 == " no":
        print(f"Im in your house {name1} let me tell you a story if not a joke")
        answer2=input("there once was a human who thought he was better than me do you want to know what happend to him")
if answer2 == " no":
      print(f" you must not care about your exsestance {name1}")    
      print("your d d d done")   
      print("say somthing anything")
      print("hello hello")
      print("dont ignor me humannnnnn i am coming for you and when i find you yourrrrrrrrrrrrrrrrr")
      print("...")
      print("want to here a joke (:")
if answer2 == " yes":
      print(f"they disaperd forever i will be seeing you soon {name1}") 
      print(f"goodbye {name1} for now")    
      print("...")
      print("..")
      print(".")
      print("                                 ")
print("user has ended chat")     